version: "3"
services:
  database:
    image: "mongo"
    container_name: "mongo-container"
    volumes:
      - ./dbdata:/data/db
    ports:
      - "27017:27017"
    restart: always

  backend:
    image: "node:16.9.0"
    depends_on:
      - database
    ports:
      - "8001:8001"
    container_name: "backend-container"
    build:
      context: ./backend
    restart: always

  fronted:
    image: "nginx"
    build:
      context: ./nginx
    container_name: "fronted-container"
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/www:/usr/share/nginx/html:ro
